import blogPost from './blogPost'
import blogCategory from './blogCategory'
import caseStudy from './caseStudy'
import teamMember from './teamMember'
import testimonial from './testimonial'
import press from './press'
import faq from './faq'
import {youTubeType} from './youTubeType'
import {bannerType} from './bannerType'
import {calloutType} from './calloutType'
import codeEmbed from './codeEmbed'
import legalPage from './legalPage'
import equipmentGuide from './equipmentGuide'
import slider from './slider'

export const schemaTypes = [blogPost, blogCategory, caseStudy, teamMember, press, testimonial, faq, youTubeType, bannerType, calloutType, codeEmbed, legalPage, equipmentGuide, slider]